#######################################################################
####                  PLAY 1: Deploy Server                         ###
#######################################################################

- name: Create EC2 server with the app
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - group_vars/env
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
  - name: Create VPC
    ec2_vpc_net:
      name: "{{ vpc_name }}"
      cidr_block: "{{ network }}"
      region: "{{ region }}"
      state: present
      dns_hostnames: yes
      dns_support: yes
      multi_ok: no
      tags:
        Name: "{{ vpc_name }}"
    register: vpc
  
  - name: Add VPC definition to vars file
    lineinfile:
      path: group_vars/aws.env
      regexp: 'vpc_id: '
      line: 'vpc_id: {{ vpc.vpc.id }}'
      state: present
      create: True
  
  - name: Associate public subnet to the VPC
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{ vpc.vpc.id }}"
      region: "{{ region }}"
      cidr: "{{ subnet_cidr }}"
      map_public: yes
      az: "{{ subnet_az }}"
      resource_tags:
        Name: "{{ vpc_name }}"
      wait: yes
    register: subnet

  - name: Add subnet definition to vars file
    lineinfile:
      path: group_vars/aws.env
      regexp: 'subnet_id: '
      line: 'subnet_id: {{ subnet.subnet.id }}'
      state: present
      create: True

  - name: Create IGW
    ec2_vpc_igw:
      vpc_id: "{{ vpc.vpc.id }}"
      region: "{{ region }}"
      state: present
      tags:
        Name: "{{ vpc_name }}_igw"
    register: igw

  - name: Add IGW definition to vars file
    lineinfile:
      path: group_vars/aws.env
      regexp: 'igw_id: '
      line: 'igw_id: {{ igw.gateway_id }}'
      state: present
      create: True

  - name: Add route table for public subnet
    ec2_vpc_route_table:
      vpc_id: "{{ vpc.vpc.id }}"
      region: "{{ region }}"
      state: present
      subnets:
        - "{{ subnet.subnet.id }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ igw.gateway_id }}"
      tags:
        Name: "{{ vpc_name }}_public_rt"
  
  - name: Create security group
    ec2_group:
      name: "{{ vpc_name }} VPC SG"
      description: "{{ vpc_name }} VPC SG"
      vpc_id: "{{ vpc.vpc.id }}"
      region: "{{ region }}"
      state: present
      rules:
        - proto: tcp
          ports:
          - 80
          - 22
          cidr_ip: 0.0.0.0/0
    register: sg
  
  - name: Create server
    ec2:
      image: "{{ aws_centos_ami }}"
      wait: yes
      instance_type: "{{ server_type }}"
      region: "{{ region }}"
      group_id: "{{ sg.group_id }}"
      vpc_subnet_id: "{{ subnet.subnet.id }}"
      key_name: "{{ keypair }}"
      volumes:
        - device_name: /dev/sda1
          volume_type: gp3
          volume_size: "{{ server_volume_size }}"
          delete_on_termination: true
      count_tag:
        Name: "{{ server_name }}"
        Environment: "{{ env }}"
      exact_count: 1
      instance_tags:
        Name: "{{ server_name }}"
        Environment: "{{ env }}"
      wait_timeout: 3000
      assign_public_ip: yes
    register: server

  - debug: var=server.tagged_instances[0].public_ip

  - name: Add server public IP to application host group
    add_host: hostname={{ server.tagged_instances[0].public_ip }} groups=app

  - name: Wait for SSH to start using external IP
    wait_for:
      host: "{{ server.tagged_instances[0].public_ip }}"
      port: 22
      timeout: 300

#######################################################################
####                     PLAY 2: Deploy App                         ###
#######################################################################

- name: Setup app server
  hosts: app
  user: centos
  become: True
  gather_facts: True
  vars_files:
    - group_vars/env
    - group_vars/docker.env
  
  tasks:
    - name: Install epel base packages
      yum:
        name:
          - epel-release
        state: present

    - name: Install base packages
      yum:
        name:
          - git
        state: present

    - name: Add singing key
      rpm_key:
        key: "https://download.docker.com/linux/centos/gpg"
        state: present

    - name: Add docker repository into repo.d list
      yum_repository:
        name: docker
        description: docker repository
        baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
        enabled: true
        gpgcheck: true
        gpgkey: "https://download.docker.com/linux/centos/gpg"

    - name: Install Docker
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true

    - name: Restart Docker service
      service:
        name: "docker"
        enabled: true
        state: restarted

    - name: Copy ssh private key
      copy:
        src: ~/.ssh/id_rsa
        dest: ~/.ssh/id_rsa
        mode: '0600'

    - name: Clone grocery app repo
      git:
        repo: git@github.com:college-devops-team/college-devops-project.git
        dest: /opt/app
        version: main
        key_file: ~/.ssh/id_rsa
        accept_hostkey: yes
        force: yes

    - name: Build docker image and push to DockerHub
      shell: "{{ item }}"
      args:
        chdir: /opt/app
      with_items:
        - docker login -u {{ docker_user }} -p {{ docker_token }}
        - docker build . --tag {{ docker_user }}/grocery_list:latest
        - docker push {{ docker_user }}/grocery_list:latest

    - name: Removing grocery app docker container if exists
      shell: "docker rm --force grocery_list"

    - name: Start grocery app docker container
      shell: "docker run -d -p 80:3000 -t --restart always --name grocery_list {{ docker_user }}/grocery_list:latest"
